import { defineConfig } from "vitest/config";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      "@obx/platform": path.join(root, "platform/src/index.ts"),
      "@obx/jobs": path.join(root, "jobs/src/index.ts"),
      "@obx/vfs": path.join(root, "vfs/src/index.ts"),
      "@obx/resources": path.join(root, "resources/src/index.ts"),
      "@obx/core": path.join(root, "core/src/index.ts"),
      "@obx/runtime": path.join(root, "runtime/src/index.ts"),
      "@obx/ecs": path.join(root, "ecs/src/index.ts"),
      "@obx/engine": path.join(root, "engine/src/index.ts"),
      "@obx/math": path.join(root, "math/src/index.ts"),
      "@obx/input": path.join(root, "input/src/index.ts"),
      "@obx/rendering": path.join(root, "rendering/src/index.ts"),
      "@obx/scene": path.join(root, "scene/src/index.ts"),
      "@obx/physics": path.join(root, "physics/src/index.ts"),
      "@obx/audio": path.join(root, "audio/src/index.ts"),
      "@obx/animation": path.join(root, "animation/src/index.ts"),
      "@obx/character": path.join(root, "character/src/index.ts"),
      "@obx/ui": path.join(root, "ui/src/index.ts"),
      "@obx/save": path.join(root, "save/src/index.ts"),
      "@obx/vehicle": path.join(root, "vehicle/src/index.ts"),
      "@obx/particles": path.join(root, "particles/src/index.ts"),
      "@obx/vfx": path.join(root, "vfx/src/index.ts"),
      "@obx/world": path.join(root, "world/src/index.ts"),
      "@obx/navigation": path.join(root, "navigation/src/index.ts"),
      "@obx/ai": path.join(root, "ai/src/index.ts"),
      "@obx/inventory": path.join(root, "inventory/src/index.ts"),
      "@obx/dialogue": path.join(root, "dialogue/src/index.ts"),
      "@obx/quest": path.join(root, "quest/src/index.ts"),
      "@obx/obsiscript": path.join(root, "obsiscript/src/index.ts"),
      "@obx/scripting": path.join(root, "scripting/src/index.ts"),
      "@obx/native": path.join(root, "native/src/index.ts"),
      "@obx/editor": path.join(root, "editor/src/index.ts"),
      "@obx/project": path.join(root, "project/src/index.ts"),
      "@obx/extensions": path.join(root, "extensions/src/index.ts"),
      "@obx/networking": path.join(root, "networking/src/index.ts"),
      "@obx/server": path.join(root, "server/src/index.ts"),
      "@obx/build": path.join(root, "builder/src/index.ts"),
      "@obx/cli": path.join(root, "cli/src/index.ts"),
      "@obx/multiplayer": path.join(root, "multiplayer/src/index.ts"),
      "@obx/profiler": path.join(root, "profiler/src/index.ts"),
      "@obx/plugins": path.join(root, "plugins/src/index.ts"),
      "@obx/registry": path.join(root, "registry/src/index.ts"),
    },
  },
  test: {
    include: [
      "platform/tests/**/*.test.ts",
      "jobs/tests/**/*.test.ts",
      "vfs/tests/**/*.test.ts",
      "resources/tests/**/*.test.ts",
      "core/tests/**/*.test.ts",
      "runtime/tests/**/*.test.ts",
      "ecs/tests/**/*.test.ts",
      "engine/tests/**/*.test.ts",
      "math/tests/**/*.test.ts",
      "input/tests/**/*.test.ts",
      "rendering/tests/**/*.test.ts",
      "scene/tests/**/*.test.ts",
      "physics/tests/**/*.test.ts",
      "audio/tests/**/*.test.ts",
      "animation/tests/**/*.test.ts",
      "character/tests/**/*.test.ts",
      "ui/tests/**/*.test.ts",
      "save/tests/**/*.test.ts",
      "vehicle/tests/**/*.test.ts",
      "particles/tests/**/*.test.ts",
      "vfx/tests/**/*.test.ts",
      "world/tests/**/*.test.ts",
      "navigation/tests/**/*.test.ts",
      "ai/tests/**/*.test.ts",
      "inventory/tests/**/*.test.ts",
      "dialogue/tests/**/*.test.ts",
      "quest/tests/**/*.test.ts",
      "obsiscript/tests/**/*.test.ts",
      "scripting/tests/**/*.test.ts",
      "native/tests/**/*.test.ts",
      "editor/tests/**/*.test.ts",
      "project/tests/**/*.test.ts",
      "extensions/tests/**/*.test.ts",
      "networking/tests/**/*.test.ts",
      "server/tests/**/*.test.ts",
      "builder/tests/**/*.test.ts",
      "cli/tests/**/*.test.ts",
      "multiplayer/tests/**/*.test.ts",
      "profiler/tests/**/*.test.ts",
      "plugins/tests/**/*.test.ts",
      "registry/tests/**/*.test.ts",
      "tests/**/*.test.ts",
    ],
    environment: "node",
    globals: false,
  },
});
