export {
  AssetIndex,
  CURRENT_FORMAT,
  PROJECT_VERSION,
  Project,
  ProjectError,
  createManifest,
  defaultSettings,
  migrateManifest,
  parseVersion,
  satisfies,
  standardFolders,
  type AssetRecord,
  type ManifestInput,
  type ProjectDependency,
  type ProjectFile,
  type ProjectManifest,
  type SettingValue,
} from "./project.js";
