export {
  AnimationTrack,
  AnimationClip,
  AnimationPlayer,
  AnimationStateMachine,
  BlendTree1D,
  Skeleton,
  blendValues,
  blendPoses,
  applyLayer,
  rootMotion,
  slerp,
  twoBoneIK,
  type AnimValue,
  type Keyframe,
  type Interpolation,
  type Pose,
  type StateCondition,
  type StateDefinition,
  type TransitionDefinition,
  type BlendTreeEntry,
  type BoneDefinition,
  type BonePose,
  type RootMotionDelta,
  type TwoBoneIkResult,
} from "./animation.js";

export const ANIMATION_VERSION = "0.5.0";
